# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: aquatics_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: aquatics_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: aquatics_production
  pool: 5
  username: 
  password:
